set nocompatible
filetype off

set exrc
set secure

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-syntastic/syntastic' "Syntax checker / linting
Plugin 'pangloss/vim-javascript' "javascript syntax highlighting
Plugin 'scrooloose/nerdtree' "file browser
Plugin 'scrooloose/nerdcommenter' "tool for commenting code
Plugin 'mxw/vim-jsx' "React/JSX syntax highlighting
Plugin 'rking/ag.vim' "Access Ag from vim
Plugin 'ctrlp.vim' "File searcher
Plugin 'terryma/vim-expand-region' "easily expand visual mode selection
Plugin 'Valloric/YouCompleteMe' "Code completion
Plugin 'vim-airline' "Status/tab line plugin
Plugin 'vim-airline/vim-airline-themes'
Plugin 'airblade/vim-gitgutter'
Plugin 'tomasr/molokai' "color scheme
Plugin 'jlanzarotta/bufexplorer' "Plugin for managing buffers
Plugin 'easymotion/vim-easymotion' "Plugin for simplifying motion commands
Plugin 'haya14busa/incsearch.vim' "Incremental Search
Plugin 'tpope/vim-surround' "for wrapping text
Plugin 'Yggdroot/indentLine' "Indentation guides
Plugin 'tpope/vim-fugitive' "Git integration
Plugin 'qpkorr/vim-bufkill' "better buffer killing
Plugin 'Xuyuanp/nerdtree-git-plugin' "Nerdtree Git plugin

call vundle#end()
filetype plugin indent on

colorscheme Molokai
set noswapfile
set showcmd
set number
syntax on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set backspace=indent,eol,start
set conceallevel=0 "don't hide quotes in JSON
set updatetime=250
set showbreak=└
let mapleader="\<Space>"

set noerrorbells
set novisualbell
autocmd! GUIEnter * set vb t_vb=

autocmd filetype crontab setlocal nobackup nowritebackup

set wildchar=<Tab> wildmenu wildmode=full "Tab completion for buffers/commands
set wildcharm=<C-z>
"Replace vim buffer kill with bufkill
nnoremap <Leader>bd :BD<CR>
"Use gB to go to previous buffer
nnoremap gB :bp<CR>
"Use gb to go to next buffer
nnoremap gb :bn<CR>
"Open Buffer List with Space+v
nnoremap <Leader>v :b <C-z>
"Open BufExplorer with Space+b
nnoremap <Leader>b :BufExplorer<CR>
let g:bufExplorerShowRelativePath=1

map q: :q
"command W :execute ':silent w !sudo tee % > /dev/null' | :edit!

"Incremental Search mappings
map / <Plug>(incsearch-forward)
map ? <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
set hlsearch
let g:incsearch#auto_nohlsearch = 1
map n <Plug>(incsearch-nohl-n)
map N <Plug>(incsearch-nohl-N)

"Easymotion mappings
map <Leader>w <Plug>(easymotion-bd-w)
map <Leader>L <Plug>(easymotion-bd-jk)

"Open CtrlP with Space+o
nnoremap <Leader>o :CtrlP<CR>
"Save with Space+w
"nnoremap <Leader>w :w<CR>
"Move to window below with C-j
nnoremap <C-J> <C-W><C-J>
"Move to window above with C-k
nnoremap <C-K> <C-W><C-K>
"Move to window right with C-l
nnoremap <C-L> <C-W><C-L>
"Move to window left with C-h
nnoremap <C-H> <C-W><C-H>

"Nerdcommenter
map <Leader>/ <Plug>NERDCommenterToggle


"use vim-expand-region with repeated presses of the v key in visual mode
vmap v <Plug>(expand_region_expand)
"shrink vim-expand-region with C-v
vmap <C-v> <Plug>(expand_region_shrink)

set wildignore+=*/node_modules/*,*.so,*.swp,*.zip,*/tmp/*
let g:jsx_ext_required = 0
"C-n to open/close NERDTree
map <C-n> :NERDTreeToggle<CR>

let g:indentLine_char = '│'

let g:ycm_autoclose_preview_window_after_completion = 1

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exe = '$(npm bin)/eslint'

set laststatus=2 "Keep status line visible
let g:airline_theme='powerlineish'
let g:airline_left_sep=''
let g:airline_left_alt_sep='|'
let g:airline_right_sep=''
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

let g:ag_working_path_mode='r'
let g:ag_highlight=1

let g:ctrlp_use_caching = 0
if executable('ag') "Use Ag (the silver searcher) for CtrlP
    set grepprg=ag\ --nogroup\ --nocolor

    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
else
    let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
endif

