require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.lualine"
require "user.bufferline"
require "user.nvimtree"

vim.cmd "colorscheme gruvbox"
-- vim.cmd "set completeopt=menu,menuone,noselect"

